"""End-to-end orchestration tying the pipeline stages together (§3.1, §3.2).

Wires the building blocks into the two product actions:
- **new pack**  — canonical → sheet → slice → emojis → publish → persist;
- **add to pack** — reuse the saved character's canonical, generate, append.

The canonical is saved once on the Character and **reused** for every pack about
that person (§3.2 / §B.4), so packs stay stylistically consistent.
"""

from __future__ import annotations

import asyncio
import contextlib
import hashlib
import json
import logging
import shutil
import time
import uuid
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path

from sticker_service.config import get_settings
from sticker_service.db import Character, Database, Pack, Sticker
from sticker_service.db.models import SubjectType
from sticker_service.services.canonical.engine import CanonicalEngine
from sticker_service.services.canonical.loader import StyleLoader
from sticker_service.services.canonical.schema import Style
from sticker_service.services.models.base import ImageModel
from sticker_service.services.postprocess import apply_watermark, grid_for, process_sheet
from sticker_service.services.publish import (
    MAX_STICKERS_PER_SET,
    Publisher,
    capacity_error,
)
from sticker_service.services.publish.naming import build_set_name
from sticker_service.services.publish.publisher import StickerInput
from sticker_service.services.stickers import (
    MAX_CAPTIONS,
    PER_PAGE,
    assign_emojis,
    build_caption_set,
    generate_sheet,
)

logger = logging.getLogger(__name__)

# Awaited with a short stage label as work really progresses ("sheet", "clean",
# "slice", "emoji", "publish") — the flow renders these as live status lines.
StageCallback = Callable[[str], Awaitable[None]]
StepCallback = Callable[[int, int], Awaitable[None]]


class OrchestratorError(RuntimeError):
    """A pipeline stage could not complete."""


def _batch_digest(stickers: list[StickerInput]) -> str:
    """Stable identity of a sticker batch (resume only ever applies to the SAME batch)."""
    import hashlib

    h = hashlib.sha256()
    for image, emoji in stickers:
        h.update(len(image).to_bytes(8, "big"))
        h.update(image)
        h.update(emoji.encode())
    return h.hexdigest()


def _read_json(path: Path) -> dict[str, object] | None:
    """Read a small JSON file; None when missing or unreadable."""
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError):
        return None


def _canonical_job_key(
    photo: bytes, style_id: str, subject_type: SubjectType, child_age: int | None
) -> str:
    """Stable identity of one canonical job (resume only applies to the SAME job)."""
    h = hashlib.sha256()
    h.update(photo)
    h.update(style_id.encode())
    h.update(str(subject_type).encode())
    h.update(str(child_age).encode())
    return h.hexdigest()[:16]


def _load_pending_steps(pending: Path, key: str) -> dict[int, bytes]:
    """Load persisted canonical steps for resume; {} (and cleanup) on a key mismatch."""
    meta = _read_json(pending / "meta.json")
    if meta is None:
        return {}
    if meta.get("key") != key:  # different photo/style — stale leftovers, drop them
        shutil.rmtree(pending, ignore_errors=True)
        return {}
    raw_steps = meta.get("steps")
    steps: dict[int, bytes] = {}
    for n in raw_steps if isinstance(raw_steps, list) else []:
        with contextlib.suppress(OSError, ValueError):
            steps[int(n)] = (pending / f"step{int(n)}.png").read_bytes()
    return steps


def _save_pending_step(pending: Path, key: str, step: int, image: bytes) -> None:
    """Persist one finished canonical step so a killed run can resume from it."""
    pending.mkdir(parents=True, exist_ok=True)
    (pending / f"step{step}.png").write_bytes(image)
    meta = _read_json(pending / "meta.json")
    done: set[int] = set()
    if meta is not None and meta.get("key") == key and isinstance(meta.get("steps"), list):
        done = {int(s) for s in meta["steps"]}  # type: ignore[union-attr]
    done.add(step)
    (pending / "meta.json").write_text(json.dumps({"key": key, "steps": sorted(done)}))


@dataclass(frozen=True)
class PackResult:
    """Outcome of building a pack."""

    set_name: str
    link: str
    count: int


@dataclass(frozen=True)
class ReviewBundle:
    """Everything the review/preview step needs after generation, before publish.

    The generated bytes are also persisted on disk so the FSM never has to
    carry them: ``fresh``/``reuse`` keep them in the draft pack (``pack_id``),
    ``extend`` in a scratch directory (``scratch_path``) — the target pack must
    not get rows for stickers that are not in the Telegram set yet.
    """

    character: Character
    stickers: list[StickerInput]
    title: str
    pack_id: int | None
    mode: str
    scratch_path: str | None = None


class Orchestrator:
    """Coordinates canonical generation, sheet build, slicing, and publishing."""

    def __init__(
        self,
        *,
        model: ImageModel,
        db: Database,
        publisher: Publisher,
        loader: StyleLoader,
        storage_dir: Path,
        engine: CanonicalEngine | None = None,
    ) -> None:
        self._model = model
        self._db = db
        self._publisher = publisher
        self._loader = loader
        self._storage = Path(storage_dir)
        self._engine = engine or CanonicalEngine(model)
        # Global gate for CPU/RAM-heavy sheet postprocessing: each 4K key+slice
        # holds ~0.6-0.9 GB and ~7 s of CPU, so concurrent users must queue here
        # instead of stacking memory peaks until the box OOMs (CAPACITY.md).
        self._postprocess_gate = asyncio.Semaphore(max(1, get_settings().postprocess_concurrency))

    async def build_canonical(
        self,
        *,
        photo: bytes,
        style_id: str,
        subject_type: SubjectType,
        child_age: int | None,
        on_step: StepCallback | None = None,
        owner_id: int | None = None,
    ) -> bytes:
        """Run the canonical pipeline for a style; returns canonical bytes.

        With ``owner_id`` each finished pipeline step is persisted to disk, so a
        re-run of the SAME job (photo+style+subject) — after a redeploy kill or
        an overload failure — RESUMES from the last completed step instead of
        regenerating (and re-paying for) the work already done.
        """
        style = self._require_style(style_id)
        pending = self._canonical_pending_dir(owner_id) if owner_id is not None else None
        key = _canonical_job_key(photo, style_id, subject_type, child_age)
        done_steps: dict[int, bytes] = {}
        if pending is not None:
            done_steps = await asyncio.to_thread(_load_pending_steps, pending, key)
            if done_steps:
                logger.info(
                    "canonical resume: owner=%s has %d step(s) done, continuing",
                    owner_id,
                    len(done_steps),
                )

        async def _persist_step(step: int, image: bytes) -> None:
            if pending is not None:
                await asyncio.to_thread(_save_pending_step, pending, key, step, image)

        canonical = await self._engine.run(
            style,
            photo,
            subject_type=subject_type,
            child_age=child_age,
            on_step=on_step,
            done_steps=done_steps or None,
            on_step_done=_persist_step if pending is not None else None,
        )
        if pending is not None:  # finished — the steps have served their purpose
            await asyncio.to_thread(shutil.rmtree, pending, True)
        return canonical

    def _canonical_pending_dir(self, owner_id: int) -> Path:
        return self._storage / "canonical_pending" / str(owner_id)

    async def validate_photo(self, image: bytes) -> str | None:
        """Vision foolproof check on upload; returns a problem code or None."""
        from sticker_service.services.photo_check import validate_photo

        return await validate_photo(self._model, image)

    async def save_character(
        self,
        *,
        owner_id: int,
        name: str,
        style_id: str,
        subject_type: SubjectType,
        child_age: int | None,
        canonical: bytes,
        photo: bytes | None = None,
    ) -> Character:
        """Persist the confirmed canonical as a reusable Character (§3.2).

        The source ``photo`` is kept too (alpha) so the canonical can be inspected
        and redrawn later.
        """
        path = await asyncio.to_thread(
            self._write, self._storage / "canonical" / f"{owner_id}_{name}.png", canonical
        )
        photo_path = (
            str(
                await asyncio.to_thread(
                    self._write, self._storage / "photos" / f"{owner_id}_{name}.jpg", photo
                )
            )
            if photo
            else None
        )
        return await self._db.add_character(
            owner_id=owner_id,
            name=name,
            style_id=style_id,
            subject_type=subject_type,
            child_age=child_age,
            canonical_path=str(path),
            photo_path=photo_path,
        )

    async def redraw_canonical(
        self,
        character: Character,
        photo: bytes,
        *,
        on_step: StepCallback | None = None,
    ) -> bytes:
        """Rebuild a character's canonical from a fresh photo, replacing the old one."""
        canonical = await self.build_canonical(
            photo=photo,
            style_id=character.style_id,
            subject_type=character.subject_type,
            child_age=character.child_age,
            on_step=on_step,
            owner_id=character.owner_id,
        )
        path = await asyncio.to_thread(
            self._write,
            self._storage / "canonical" / f"{character.owner_id}_{character.name}.png",
            canonical,
        )
        photo_path = await asyncio.to_thread(
            self._write,
            self._storage / "photos" / f"{character.owner_id}_{character.name}.jpg",
            photo,
        )
        await self._db.update_character_canonical(
            character.id, canonical_path=str(path), photo_path=str(photo_path)
        )
        return canonical

    async def build_stickers(
        self,
        character: Character,
        *,
        captions: list[str] | None = None,
        on_stage: StageCallback | None = None,
    ) -> list[StickerInput]:
        """Generate the sliced stickers (sheet → slice → emoji) WITHOUT publishing.

        ``captions`` lets the caller pass an explicit set (selected standard +
        custom). Pages of >12 are generated as separate sheets. Used to show a
        preview before the user confirms publication.
        """
        stickers, emojis = await self._generate_stickers(character, captions, on_stage)
        return list(zip(stickers, emojis, strict=True))

    async def build_for_review(
        self,
        *,
        mode: str,
        owner_id: int,
        captions: list[str],
        on_step: StepCallback | None = None,
        on_stage: StageCallback | None = None,
        photo: bytes | None = None,
        style_id: str | None = None,
        subject_type: SubjectType | None = None,
        child_age: int | None = None,
        name: str | None = None,
        character_id: int | None = None,
        pack_id: int | None = None,
    ) -> ReviewBundle:
        """Resolve the character (fresh/reuse/extend), generate stickers, save a draft.

        Centralises the three-mode branching that the conversational flow used to
        inline, so the generate→draft path is testable end-to-end (e.g. with the
        mock model). ``extend`` appends to an existing pack and does not save a new
        draft; ``fresh``/``reuse`` persist an unpublished draft for later publish.
        """
        if mode == "extend":
            if pack_id is None:
                raise OrchestratorError("extend mode needs a pack_id")
            pack = await self._db.get_pack(pack_id)
            if pack is None:
                raise OrchestratorError("pack not found")
            # Capacity pre-check BEFORE generating (and before the caller charges):
            # an extend that can't fit the 120-sticker limit must fail for free,
            # not after a paid generation that publish_extend would then reject.
            current = await self._db.count_stickers(pack.id)
            if len(captions) + current > MAX_STICKERS_PER_SET:
                raise capacity_error(pack.title, current)
            character = await self._db.get_character(pack.character_id)
            title: str = pack.title
        elif mode == "reuse":
            if character_id is None:
                raise OrchestratorError("reuse mode needs a character_id")
            character = await self._db.get_character(character_id)
            title = character.name if character else ""
            pack_id = None
        else:  # fresh — build the canonical now
            if photo is None or style_id is None or subject_type is None:
                raise OrchestratorError("fresh mode needs photo, style_id and subject_type")
            canonical = await self.build_canonical(
                photo=photo,
                style_id=style_id,
                subject_type=subject_type,
                child_age=child_age,
                on_step=on_step,
                owner_id=owner_id,
            )
            character = await self.save_character(
                owner_id=owner_id,
                name=name or "Мой пак",
                style_id=style_id,
                subject_type=subject_type,
                child_age=child_age,
                canonical=canonical,
                photo=photo,
            )
            title = character.name
            pack_id = None
        if character is None:
            raise OrchestratorError("character not found")
        stickers = await self.build_stickers(character, captions=captions, on_stage=on_stage)
        scratch_path: str | None = None
        if mode == "extend":
            # No draft pack for extend (rows in the target would lie about the
            # set's real size) — park the bytes in a scratch dir until publish.
            scratch_path = await self.save_scratch(owner_id=owner_id, stickers=stickers)
        else:
            draft = await self.save_draft(
                owner_id=owner_id, character=character, title=title, stickers=stickers
            )
            pack_id = draft.id
        return ReviewBundle(
            character=character,
            stickers=stickers,
            title=title,
            pack_id=pack_id,
            mode=mode,
            scratch_path=scratch_path,
        )

    async def publish_new(
        self,
        *,
        owner_id: int,
        character: Character,
        stickers: list[StickerInput],
        title: str | None = None,
    ) -> PackResult:
        """Publish already-generated stickers as a new Telegram set + persist."""
        title = title or character.name
        logger.info("publish: creating set owner=%s title=%s", owner_id, title)
        set_name = await self._publisher.create_pack(
            user_id=owner_id, title=title, stickers=list(stickers)
        )
        pack = await self._db.add_pack(
            character_id=character.id,
            owner_id=owner_id,
            set_name=set_name,
            title=title,
            published=True,
        )
        await self._persist_pairs(pack, stickers, start=0)
        logger.info("publish: done set=%s stickers=%d", set_name, len(stickers))
        return PackResult(set_name, self._publisher.link(set_name), len(stickers))

    async def save_draft(
        self,
        *,
        owner_id: int,
        character: Character,
        title: str,
        stickers: list[StickerInput],
    ) -> Pack:
        """Persist generated stickers as an UNPUBLISHED pack for later publish/download."""
        # Hidden machine name reserved now; replaced with the real one on publish.
        placeholder = build_set_name(title, self._publisher.bot_username)
        pack = await self._db.add_pack(
            character_id=character.id,
            owner_id=owner_id,
            set_name=placeholder,
            title=title,
            published=False,
        )
        await self._persist_pairs(pack, stickers, start=0)
        logger.info("draft saved: pack=%s stickers=%d", pack.id, len(stickers))
        return pack

    async def publish_draft(
        self, *, owner_id: int, pack: Pack, stickers: list[StickerInput]
    ) -> PackResult:
        """Publish a previously-saved draft pack to Telegram and mark it published."""
        set_name = await self._publisher.create_pack(
            user_id=owner_id, title=pack.title, stickers=list(stickers)
        )
        await self._db.update_pack(pack.id, set_name=set_name, published=True)
        logger.info("publish draft: pack=%s set=%s", pack.id, set_name)
        return PackResult(set_name, self._publisher.link(set_name), len(stickers))

    async def load_pack_stickers(self, pack_id: int) -> list[StickerInput]:
        """Read a pack's persisted sticker files + emoji from disk."""
        rows = await self._db.list_stickers(pack_id)
        return await asyncio.to_thread(
            lambda: [(Path(s.file_path).read_bytes(), s.emoji) for s in rows]
        )

    # --- scratch: review-stage bytes for extend (no draft pack to hold them) --

    @property
    def _scratch_root(self) -> Path:
        return self._storage / "scratch"

    async def save_scratch(self, *, owner_id: int, stickers: list[StickerInput]) -> str:
        """Persist review-stage stickers to a scratch dir; returns its path.

        Keeps generated bytes out of the FSM (which would otherwise grow by
        megabytes per review and block the event loop on every state write).
        """
        target = self._scratch_root / f"{owner_id}_{uuid.uuid4().hex[:8]}"

        def _write_all() -> None:
            target.mkdir(parents=True, exist_ok=True)
            for i, (image, _emoji) in enumerate(stickers):
                (target / f"{i:03d}.png").write_bytes(image)
            emojis = [emoji for _, emoji in stickers]
            (target / "emojis.json").write_text(json.dumps(emojis, ensure_ascii=False))

        await asyncio.to_thread(_write_all)
        return str(target)

    async def load_scratch(self, path: str) -> list[StickerInput]:
        """Read scratch stickers back; empty list when the dir is gone (expired)."""
        base = self._resolve_scratch(path)

        def _read_all() -> list[StickerInput]:
            # A concurrently GC'd/dropped or partially written dir degrades to
            # the documented "expired" result instead of raising mid-publish.
            try:
                if base is None or not base.is_dir():
                    return []
                emojis: list[str] = json.loads((base / "emojis.json").read_text())
                return [((base / f"{i:03d}.png").read_bytes(), e) for i, e in enumerate(emojis)]
            except (OSError, ValueError):
                return []

        return await asyncio.to_thread(_read_all)

    async def drop_scratch(self, path: str) -> None:
        """Best-effort removal of a scratch dir (after publish or cancel)."""
        base = self._resolve_scratch(path)
        if base is not None:
            await asyncio.to_thread(shutil.rmtree, base, True)

    def _resolve_scratch(self, path: str) -> Path | None:
        """Resolve a scratch path, refusing anything outside the scratch root."""
        base = Path(path).resolve()
        root = self._scratch_root.resolve()
        return base if root in base.parents else None

    async def gc_stale_drafts(self, *, older_than_days: int) -> int:
        """Delete unpublished drafts older than the window + their PNGs.

        Drafts are ephemeral (created mid-flow, then published or abandoned), so
        an old one is safe to remove; this bounds disk/DB growth on the small
        VDS. Published packs are never touched. Returns the count removed; a
        non-positive window disables the sweep.
        """
        if older_than_days <= 0:
            return 0
        cutoff = datetime.now(UTC) - timedelta(days=older_than_days)
        drafts = await self._db.list_stale_drafts(cutoff)
        for pack in drafts:
            stickers = await self._db.list_stickers(pack.id)
            await self._db.delete_pack(pack.id)
            self._remove_sticker_files(pack, stickers)
        scratch = await asyncio.to_thread(self._gc_scratch_dirs, older_than_days)
        if drafts or scratch:
            logger.info(
                "gc: removed %d stale draft pack(s), %d scratch dir(s)", len(drafts), scratch
            )
        return len(drafts)

    def _gc_scratch_dirs(self, older_than_days: int) -> int:
        """Delete scratch dirs past the retention window (abandoned extends)."""
        root = self._scratch_root
        if not root.is_dir():
            return 0
        cutoff_ts = time.time() - older_than_days * 86400
        removed = 0
        for entry in root.iterdir():
            with contextlib.suppress(OSError):
                if entry.is_dir() and entry.stat().st_mtime < cutoff_ts:
                    shutil.rmtree(entry, ignore_errors=True)
                    removed += 1
        return removed

    def _remove_sticker_files(self, pack: Pack, stickers: list[Sticker]) -> None:
        """Best-effort delete a draft's PNGs and its per-set directory."""
        for sticker in stickers:
            with contextlib.suppress(OSError):
                Path(sticker.file_path).unlink(missing_ok=True)
        set_dir = self._storage / "stickers" / pack.set_name
        with contextlib.suppress(OSError):
            if set_dir.is_dir():
                shutil.rmtree(set_dir)

    async def publish_extend(
        self, *, owner_id: int, pack: Pack, stickers: list[StickerInput]
    ) -> PackResult:
        """Append already-generated stickers to an existing set + persist.

        Crash/flood-safe: each sticker's DB row is persisted right after it
        lands in the Telegram set (the DB never lags by more than one), and a
        marker keyed by the batch digest lets a retry of the SAME batch resume
        where the set actually stopped — without ever skipping stickers because
        of unrelated live-vs-DB drift (e.g. the owner adding stickers manually).
        """
        live = await self._publisher.live_count(pack.set_name)
        skip = 0
        marker = self._extend_marker(pack.id)
        digest = _batch_digest(stickers)
        if live is not None:
            prev = await asyncio.to_thread(_read_json, marker)
            prev_live = prev.get("live_before") if prev else None
            if prev and prev.get("digest") == digest and isinstance(prev_live, int):
                skip = min(max(live - prev_live, 0), len(stickers))
                if skip:
                    logger.warning(
                        "extend resume: %s already holds %d of %d new sticker(s)",
                        pack.set_name,
                        skip,
                        len(stickers),
                    )
            live_before = live - skip
            # Repair rows for the already-landed prefix (the crash window is one
            # sticker wide thanks to per-add persistence below).
            current = await self._db.count_stickers(pack.id)
            for offset in range(max(current - live_before, 0), skip):
                await self._persist_one(pack, live_before + offset, stickers[offset])
            await asyncio.to_thread(
                self._write,
                marker,
                json.dumps({"digest": digest, "live_before": live_before}).encode(),
            )
        start = await self._db.count_stickers(pack.id)

        async def _on_added(position: int, sticker: StickerInput) -> None:
            await self._persist_one(pack, position, sticker)

        await self._publisher.add_to_pack(
            user_id=owner_id,
            set_name=pack.set_name,
            stickers=list(stickers)[skip:],
            current_count=start,
            on_added=_on_added,
        )
        await asyncio.to_thread(lambda: marker.unlink(missing_ok=True))
        return PackResult(pack.set_name, self._publisher.link(pack.set_name), len(stickers))

    def _extend_marker(self, pack_id: int) -> Path:
        return self._storage / "extend_pending" / f"{pack_id}.json"

    async def create_pack(
        self,
        *,
        owner_id: int,
        character: Character,
        title: str | None = None,
        captions: list[str] | None = None,
        on_stage: StageCallback | None = None,
    ) -> PackResult:
        """Convenience: generate + publish a new pack in one shot."""
        stickers = await self.build_stickers(character, captions=captions, on_stage=on_stage)
        await self._stage(on_stage, "publish")
        return await self.publish_new(
            owner_id=owner_id, character=character, stickers=stickers, title=title
        )

    async def extend_pack(
        self,
        *,
        owner_id: int,
        pack: Pack,
        captions: list[str] | None = None,
        on_stage: StageCallback | None = None,
    ) -> PackResult:
        """Convenience: generate + append to an existing pack in one shot (§3.2)."""
        character = await self._db.get_character(pack.character_id)
        if character is None:  # pragma: no cover - referential integrity
            raise OrchestratorError(f"pack {pack.id} references missing character")
        stickers = await self.build_stickers(character, captions=captions, on_stage=on_stage)
        await self._stage(on_stage, "publish")
        return await self.publish_extend(owner_id=owner_id, pack=pack, stickers=stickers)

    # --- internals -----------------------------------------------------------

    async def _generate_stickers(
        self,
        character: Character,
        captions: list[str] | None,
        on_stage: StageCallback | None = None,
    ) -> tuple[list[bytes], list[str]]:
        style = self._require_style(character.style_id)
        canonical = await asyncio.to_thread(Path(character.canonical_path).read_bytes)
        captions = (captions if captions is not None else build_caption_set())[:MAX_CAPTIONS]
        pages = [captions[i : i + PER_PAGE] for i in range(0, len(captions), PER_PAGE)]
        stickers: list[bytes] = []
        # Stage labels are emitted right BEFORE the work they describe, so the
        # live status line always tells the truth about what is running now.
        for page_no, page in enumerate(pages, start=1):
            await self._stage(on_stage, "sheet")
            logger.info("sheet: page %d/%d (%d captions)", page_no, len(pages), len(page))
            sheet = await generate_sheet(
                self._model,
                canonical,
                style,
                page,
                subject_type=character.subject_type,
                child_age=character.child_age,
            )
            await self._stage(on_stage, "clean")
            # Chroma keying + component labeling over a 4K sheet is seconds of
            # numpy/PIL CPU — off the event loop, or every other user stalls;
            # and through the gate, or concurrent users stack ~0.7 GB peaks.
            sliced = await self._gated_to_thread(
                lambda s=sheet, p=page: process_sheet(s, grid=grid_for(len(p)), expected=len(p))
            )
            await self._stage(on_stage, "slice")
            stickers.extend(sliced)
        if not stickers:  # pragma: no cover - defensive
            raise OrchestratorError("slicing produced no stickers")
        settings = get_settings()
        if settings.watermark_enabled:
            stickers = await self._gated_to_thread(
                lambda ss=stickers: [apply_watermark(s, text=settings.watermark_text) for s in ss]
            )
        logger.info("slice: produced %d stickers total", len(stickers))
        await self._stage(on_stage, "emoji")
        emojis = await assign_emojis(self._model, stickers, captions)
        return stickers, emojis

    async def _gated_to_thread[T](self, fn: Callable[[], T]) -> T:
        """Run CPU-heavy ``fn`` in a thread under the postprocess gate.

        The gate slot is released only when the thread actually exits — not
        when the awaiting coroutine is cancelled (generation timeout). A
        cancelled wait cannot abort the keying thread anyway, so releasing
        early would let parallel cancellations stack untracked ~0.7 GB peaks.
        """
        await self._postprocess_gate.acquire()

        def _release(t: asyncio.Task[T]) -> None:
            self._postprocess_gate.release()
            if not t.cancelled():
                t.exception()  # retrieved: an abandoned failure must not warn-spam

        task = asyncio.create_task(asyncio.to_thread(fn))
        task.add_done_callback(_release)
        return await asyncio.shield(task)

    @staticmethod
    async def _stage(on_stage: StageCallback | None, label: str) -> None:
        logger.info("stage: %s", label)
        if on_stage is not None:
            await on_stage(label)

    async def _persist_pairs(self, pack: Pack, stickers: list[StickerInput], *, start: int) -> None:
        for offset, sticker in enumerate(stickers):
            await self._persist_one(pack, start + offset, sticker)

    async def _persist_one(self, pack: Pack, position: int, sticker: StickerInput) -> None:
        """Write one sticker's PNG + DB row at ``position`` in the pack."""
        image, emoji = sticker
        path = await asyncio.to_thread(
            self._write,
            self._storage / "stickers" / pack.set_name / f"{position:03d}.png",
            image,
        )
        await self._db.add_sticker(
            pack_id=pack.id, file_path=str(path), emoji=emoji, position=position
        )

    def _require_style(self, style_id: str) -> Style:
        style = self._loader.get(style_id)
        if style is None:
            raise OrchestratorError(f"unknown or invalid style: {style_id!r}")
        return style

    @staticmethod
    def _write(path: Path, data: bytes) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return path
